version: '3.3'
services:
  database:
    image: mysql:8
    volumes:
      - pi_data:/var/lib/mysql
      - ./primera_infancia.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: unless-stopped
    ports:
      - "3306:3306"

  api-springboot:
    image: primera-infancia/springboot
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=database
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_NAME=${MYSQL_DATABASE}
    depends_on: [database]
    restart: unless-stopped

  web-client:
    image: primera-infancia/angular
    ports:
      - "80:80"
    environment:
      - BASE_URL=${BASE_URL}
    restart: unless-stopped

volumes:
  pi_data:
    external: true