version: '3.3'
services:
  database:
    image: mysql:8
    volumes:
      - pi_data:/var/lib/mysql
      - ./primera_infancia.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: unless-stopped
    ports:
      - "3306:3306"

  api-springboot:
    image: primera-infancia/springboot
    ports:
      - 8080:8080
    environment:
      - MYSQL_HOST=database
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_NAME=${MYSQL_DATABASE}
    depends_on: [database]
    restart: unless-stopped

  web-client:
    image: manuminnig/pi-angular:1.0.1
    environment:
      - BASE_URL=${BASE_URL}
    restart: unless-stopped

#  caddy:
#    image: caddy:2.7-alpine
#    restart: always
#    cap_add:
#      - NET_ADMIN
#    ports:
#      - "80:80"
#      - "443:443"
#      - "443:443/udp"
#    volumes:
#      - ./Caddyfile:/etc/caddy/Caddyfile
#      - caddy_data:/data
#      - caddy_config:/config
#
#  portainer-ce:
#    ports:
#      - 8000:8000
#      - 9443:9443
#      - 9000:9000
#    container_name: portainer
#    restart: always
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - portainer_data:/data
#    image: portainer/portainer-ce:latest


volumes:
  # caddy_data:
  # caddy_config:
  pi_data:
  # portainer_data:
  #   external: true
