version: '3.3'
services:
  database:
    image: mysql:8
    volumes:
      - pi_data:/var/lib/mysql
      - ./primera_infancia.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: unless-stopped
    ports:
      - "3306:3306"

  api-springboot:
    image: primera-infancia/springboot
    ports:
      - 8080:8080
    environment:
      - MYSQL_HOST=database
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_NAME=${MYSQL_DATABASE}
    depends_on: [database]
    restart: unless-stopped

  web-client:
    image: primera-infancia/angular
    environment:
      - BASE_URL=${BASE_URL}
    restart: unless-stopped

  caddy:
    image: caddy:2.7-alpine
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  pi_data:

