version: '3.8'
services:
  pidb:
    image:
      mysql
    ports:
      - "13306:3306"
    environment:
      - MYSQL_USER=priminf
      - MYSQL_PASSWORD=admin
    restart:
      no
  primerainfanciaapi:
    build:
      /home/solemerino/Sole/PrimeraInfancia/primeraInfanciaRest
    ports:
      - "18080:8080"
    depends_on:
      - pidb
    restart:
      on-failure
  primerainfanciaclient:
    build:
      /home/solemerino/Sole/PrimeraInfancia/primera-infancia
    ports:
      - "80:80"
    depends_on:
      - pidb
      - primerainfanciaapi
    restart:
      on-failure